language: ruby
sudo: false
cache: bundler

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - jruby-head
  - ruby-head
  - rbx-3
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: rbx-3
