language: ruby
sudo: false
dist: trusty
cache: bundler
addons:
  apt:
    packages:
      - google-chrome-stable
rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - jruby-head
  - ruby-head
  - rbx-3
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: rbx-3
